### ISSUE TITLE
Problem to deploy bridge and contracts to Polygon Mumbai

### ISSUE THREAD

**Issue by pedro-haeser-cryptotao** [ChainSafe/chainbridge-deploy#104]
I'm trying to deploy the contracts necessary for the bridge to transfer assets between different blockchains.

## Expected Behavior

When I run the command 

```
cb-sol-cli deploy --bridge \
  --erc721Handler \
  --erc721 \
  --config \
  --chainId 99 \
  --url https://polygon-mumbai.infura.io/v3/[PROJECT_ID] \
  --privateKey [PRIVATE_KEY] \
  --relayers [RELAYER_ADDRESS] \
  --relayerThreshold 1
```
The expected behavior would be to deploy the bridge, erc721handler and erc721 contracts.

I tried to use an Alchemy RPC URL, the public https://rpc-mumbai.matic.today URL as well... all of them failed.
This deployment fail seems to be specific for Polygon, since I was able to deploy the contracts to Ethereum Ropsten and Goerli

## Current Behavior

The current behavior is that when I run the command above, the CLI gets stuck with the message "Deploying contracts..."
It seems that bridge is the first contract to be deployed, and it gets stuck there for Polygon Mumbai

## Possible Solution

Not sure how to fix or troubleshoot it... any help is much appreciated.

## Steps to Reproduce (for bugs)

1. Fund an account on Polygon Mumbai testnet (you can use https://mumbaifaucet.com for example)
2. Create a polygon mumbai node on [Alchemy](https://www.alchemy.com/) or [Infura](https://infura.io/)
3. git clone https://github.com/ChainSafe/chainbridge-deploy.git
4. cd chainbridge-deploy/cb-sol-cli
5. make install
6. $ cb-sol-cli deploy --bridge \
  --erc721Handler \
  --erc721 \
  --config \
  --chainId 99 \
  --url https://polygon-mumbai.infura.io/v3/[PROJECT_ID] \
  --privateKey [PRIVATE_KEY] \
  --relayers [RELAYER_ADDRESS] \
  --relayerThreshold 1

## Versions
ChainBridge commit (or docker tag): f2aa093 on main branch
chainbridge-solidity version:
chainbridge-substrate version:
Go version:

**Comment by vineetaparodkar** [comment]
@pedro-haeser-cryptotao, You will have to submit transactions with gasprice flag. ( Gasprice flag accepts price in Wei) since default gas prices are around 1000 which is much lower than the polygon pos chain prices you will have to manually pass in to deploy command.

Cb-sol-cli docs: https://github.com/ChainSafe/chainbridge-deploy/blob/main/cb-sol-cli/README.md#usage
