### ISSUE TITLE
startBlock shows in output but not defined

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/chainbridge-deploy#25]
Currently getting chains with `opts` including `"startBlock": "",`.

Lets ensure startBlock can be specified, and is omitted from the output if not specified.

**Comment by P1sar** [comment]
@ansermino  Im not sure im properly understand the problem, can you please be more specific.

**Comment by ansermino** [comment]
For the cfgBuilder tool, the config that it outputs includes `"startBlock"` but it is set to `""` regardless of what is passed in.
