### ISSUE TITLE
Async contract deployments

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/chainbridge-deploy#26]
Would be very nice to have async deployments for contracts that can be.

**Comment by P1sar** [comment]
What do you mean by async deployment since all deployments are happen from one sender and could not be async because of nonce

**Comment by ansermino** [comment]
They could still be async, as long as they have different nonces. Waiting a whole block for each contract to deploy adds a lot of overhead, if multiple can be included in a single block it would be noticeably faster.
