### ISSUE TITLE
Fail with error 'sender doesn&#39;t have relayer role'

### ISSUE THREAD

**Issue by coursewarefactory** [ChainSafe/chainbridge-deploy#88]
I trying to execute the deposit of ERC721 from local network to Goerli

## Expected Behavior

NFT should be transferred

## Current Behavior

I am getting this error
Fail with error 'sender doesn&#39;t have relayer role'
https://goerli.etherscan.io/tx/0x2a643d2d9888d9438b6c9998121cf544148c3665f8973d6d2763521d6cc42ace

## Steps to Reproduce (for bugs)

https://goerli.etherscan.io/tx/0x2a643d2d9888d9438b6c9998121cf544148c3665f8973d6d2763521d6cc42ace

cb-sol-cli --url $SRC_GATEWAY --privateKey $SRC_PK --gasPrice 1 erc721 deposit --id 0x199 --dest 5 --resourceId $RESOURCE_ID --recipient $DST_ADDR --gasLimit 100000 --bridge $SRC_BRIDGE --gasPrice 10000000

1.
2.
3.
4.

## Versions
ChainBridge commit (or docker tag): 
chainbridge-solidity version:
chainbridge-substrate version:
Go version:

**Comment by nmlinaric** [comment]
Hi @coursewarefactory, sorry for the late response.
By the information you provided I would say that you didn't call [adminAddRelayer](https://github.com/ChainSafe/chainbridge-solidity/blob/master/contracts/Bridge.sol#L193) on your Relayerer and that should fix it.
If you have some other issues feel free to reach out.

**Comment by nmlinaric** [comment]
Closing due inactivity
